# Generated by Django 5.1.5 on 2025-02-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefectsPortal', '0002_defectslist_delete_defect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectslist',
            name='defect_type',
            field=models.CharField(choices=[('PRIMARY', 'primary'), ('SECONDARY', 'secondary')], default='primary', max_length=100),
        ),
        migrations.AlterField(
            model_name='defectslist',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'high'), ('MEDIUM', 'medium'), ('LOW', 'low')], default='high', max_length=100),
        ),
    ]
