# Generated by Django 5.1.5 on 2025-02-24 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefectsPortal', '0003_alter_defectslist_defect_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defects_screen_shots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_img', models.ImageField(blank=True, null='True', upload_to='defect_ss')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defectslists', to='DefectsPortal.defectslist')),
            ],
        ),
    ]
