# Generated by Django 5.1.5 on 2025-02-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefectsPortal', '0004_defects_screen_shots'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectslist',
            name='defect_status',
            field=models.CharField(choices=[('COMPLETED', 'completed'), ('NOT COMPLETED', 'not completed')], default='not completed', max_length=100),
        ),
    ]
