# Generated by Django 5.1.5 on 2025-02-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefectsPortal', '0005_defectslist_defect_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectslist',
            name='defect_status',
            field=models.CharField(choices=[('COMPLETED', 'completed'), ('NOT COMPLETED', 'not completed')], max_length=100),
        ),
    ]
